#!/bin/bash
export PYTHONPATH=/usr/local/bin/python2.6

# Replace these three settings.
PROJDIR="/home/<REPLACE:PROJECT_NAME>"
PIDFILE="$PROJDIR/fcgi.pid"
#SOCKET="$PROJDIR/fcgi.sock"

cd $PROJDIR
if [ -f $PIDFILE ]; then
    kill `cat -- $PIDFILE`
    rm -f -- $PIDFILE
fi

exec /usr/bin/env - \
  bin/django runfcgi method=prefork maxrequests=500 host=127.0.0.1 port=<REPLACE:FCGI_PORT> pidfile=$PIDFILE daemonize=true
