#!/bin/bash

SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname $SCRIPT`

# go one dir up
PROJECT_ROOT=`dirname $SCRIPTPATH`
cd $PROJECT_ROOT

exec \
    setuidgid <REPLACE:PROJECT_NAME> \
    bin/python manage.py run_gunicorn 127.0.0.1:<REPLACE:PORT> -w 5
